### ISSUE TITLE
Tell when a package is installed

### ISSUE THREAD

**Issue by Megver83** [victorgarric/pip_search#10]
The original `pip search` used to and [pypisearch](https://github.com/shidenko97/pypisearch) does this. For example:

```
$ pypisearch moodle-dl
moodle-dl (2.2.1.4)             [installed 2.2.1.2] A Moodle downloader that downloads course content fast from Moodle (eg. lecture pdfs)
moodle (0.0.1)                  Moodle web services connection library
xls2moodle (1.12)               xls2moodle: Import multiple-choice questions from excel to moodle.
moodle-inscribe (3.9.1)         Inscribe students into moodle courses by their email. Works with Moodle 3.9.
moodle-sdk (2.0.4)              Moodle Development Kit
```
It's a nice feature for `pip_search` to implement.

**Comment by Megver83** [comment]
fyi, pypisearch implemented the feature in [this commit](https://github.com/shidenko97/pypisearch/commit/c5cec47646d330d2bf2efaa457f63c961ef14d35)

**Comment by victorgarric** [comment]
![image](https://user-images.githubusercontent.com/6721280/147912983-9a208c42-050d-4755-ba21-c5077a03290b.png)
As you can see, when a package is installed with the latest version, it displays it and also informs you when a greater version is available
