### ISSUE TITLE
Add more info to README

### ISSUE THREAD

**Issue by eabase** [victorgarric/pip_search#12]
Hi Victor, 
Great package! Look very promising. 
Just found it just after having wasted some time making my own. 👍 

1. Can you please add the dependencies to your README?
`install_requires=['bs4', 'requests', 'rich'],`
I noticed it uses `rich` which itself have many requirements, and would be good to know before spamming your package list. 

2. What are the max length of the found/displayed packages?

**Comment by victorgarric** [comment]
Hello,

I did as requested
Fyi, the display length is equal to the first results page en pypi.org
