### ISSUE TITLE
Documentation on  https://pypi.org/project/pip-search/   

### ISSUE THREAD

**Issue by ashaypatil12** [victorgarric/pip_search#22]
1. The paragraph which states "A package to search like pip used to via PyPi". It doesn't seem to pretty clear. 
Suggested : A package to search like pip used to, via PyPi.

2. Another paragraph which states "Warping the needs of a "pip search" command necessity through PyPi.org"
Suggested : Wrapping the needs of a "pip search" command necessity through PyPi.org

**Comment by victorgarric** [comment]
Modification made accordingly
