### ISSUE TITLE
Many packages missing from results

### ISSUE THREAD

**Issue by haa-zee** [victorgarric/pip_search#35]
I'm not sure if it is a bug or my fault... I've tried to find Flask modules, using pip_search: `pip_search flask` 
The result contained about 45-50 lines. When I repeated this search on pypi.org/search, then I got more than 700 hits.

**Comment by victorgarric** [comment]
Greetings,

When using pip_search command line, the program parses the first results from pypi.org into a table. It therefore is normal for you to only get the results of the first page.

Best regards,
Victor Garric
