### ISSUE TITLE
Cannot search for **anything**

### ISSUE THREAD

**Issue by daffidwilde** [victorgarric/pip_search#41]
Hi there 👋🏼 

I am trying to use `pip_search@0.0.10` to find the [ScaNN package](https://github.com/google-research/google-research/tree/master/scann), which [exists on PyPI](https://pypi.org/project/scann/) as `scann`.

This is the traceback I receive:

```console
$ pip_search scann
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "<PATH TO ENV>\Scripts\pip_search.exe\__main__.py", line 7, in <module>
  File "<PATH TO ENV>\Lib\site-packages\pip_search\__main__.py", line 65, in main
    for package in result:
                   ^^^^^^
  File "<PATH TO ENV>\Lib\site-packages\pip_search\pip_search.py", line 98, in search
    snippet.select_one('span[class*="package-snippet__version"]').text.strip(),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'
```

I'm not sure what the cause of the issue is. I am unable to install the package on my Windows machine, but I assume I should be able to search for it on PyPI still.

**Comment by daffidwilde** [comment]
I've actually just tested this for a couple of other packages (`dask` and `hypothesis`) and get to the same issue. It looks like the version is no longer listed on PyPI search results, which is a shame.

**Comment by victorgarric** [comment]
The lastest version should work fine : https://pypi.org/project/pip-search/

pip install pip-search==0.0.13
