### ISSUE TITLE
Forced 0.0.13 install returns v. 0.0.10

### ISSUE THREAD

**Issue by nannerpusser** [victorgarric/pip_search#43]
pip_search was working, but not returning any results for anything on Windows 11 with python 3.12.8, so I did the dance of uninstall/reinstall on it after reading a closed related issue about recent errors. 

`pipx install pip-search==0.0.13
  installed package pip-search 0.0.13, installed using Python 3.12.8
  These apps are now globally available`

Immediately followed by:

`pip_search.exe --version

pip_search 0.0.10`

Still no returns on any search query. This occurs whether I use `pipx` or whether I use user-site or global python install using Windows sudo and `--break-system-packages`. All return the same version number. Is this a me problem with Windows and cache and dumb permissions somewhere, or is this the intended binary version number (0.0.10) for release 0.0.13?

EDIT: FWIW, `pypi.exe` search is not returning  anything either, or even crashing with a Traceback related to network errors, which is why I thought this was maybe not a "me" issue and something maybe even further upstream from here.

**Comment by cfosterhoudt** [comment]
I _suspect_ the lack of returns on search queries (affecting me too!) is related to yet more lock-downs at pypi. 
https://discuss.python.org/t/fastly-interfering-with-pypi-search/73597

**Comment by coz-tech** [comment]
> > I _suspect_ the lack of returns on search queries (affecting me too!) is related to yet more lock-downs at pypi. [discuss.python.org/t/fastly-interfering-with-pypi-search/73597](https://discuss.python.org/t/fastly-interfering-with-pypi-search/73597)
> 
> Well this is good news/bad news. Good that this wasn't me being a dummy or having some kind of deeper python issue locally, bad because it does sound like this is permanent going forward and just killed the few remaining non-API search tools left.
> 
> Funny thing is I was literally writing my first webscraper with `bs4` and `requests-html` right now as I got this email and I was gonna just write my own "API" like a dirty snake in the grass that I am and at least give myself a CLI tool to search pypi. Sounds like 20 million jerks from Eastern Europe are doing just that, but with malice. This Fastly protection they're using now seems to really screw up scraping methods anyway unless you manually grab a cookie and import it so python looks like an actual browser and at least the first time.

Well, dirty snake-in-the-grass, if you get something working, let us know. pip_search has been an /excellent/ tool for me, and its breaking---no fault of pip_search itself!---makes for a sad panda here.

**Comment by kernkraft235** [comment]
perhaps it could be updated to issue a statement letting the user know its broken due to pypi changes, then failover to spawning a webview of the pypi query. 

In macOS this can be a ephemeral quicklook window, or if nothing is working, at least just open the link in your default browser.
Or if we wanna get really crazy - output a screenshot from a fake chrome browser, it could look like this 
![Safari  T-2107  - Search results · PyPI 36@2x](https://github.com/user-attachments/assets/c825deb4-488d-43c1-989f-3daf28a53009)

**Comment by nannerpusser** [comment]
Just a useless followup: 

I did manage to write a working scraper that even mimics the styling of pip-search (Rich table) returns, but I could not get requests-HTML or any non-browser library solution for JS rendering to work because of the Fastly protections. I had to use Playwright, which is great and can run headless in a shell, but ultimately is  incredibly slow on account of needing a whole separate Chromium thread in combination with rate-limiting and other "user behavior" automation to avoid detection. It's actually faster to just Alt Tab to browser, and do it yourself  as long as you are quick and accurate on a keyboard 🥲
