### ISSUE TITLE
Folder link not working

### ISSUE THREAD

**Issue by tik9** [victorgarric/pip_search#9]
![screen](https://user-images.githubusercontent.com/3178925/143268100-924ac092-faa8-4a0f-841f-950dd518f26f.jpg)
I cannot do the folder linking in the leftmost column.
When I press ctrl and hove the mouse over the name, there is no link possible.

I use Ubuntu 20.04 with qterminal version `0.14.1`.

**Comment by RCristiano** [comment]
I use fish shell in kitty terminal and `ctrl+shift` makes the magic for me.
What's the shell you uses?
